routes/web.php
<?php

use \App\Pelicula;
use \App\Productor;
use \App\Genero;
use \App\Mail\FichaPelicula;

Route::get('/email/enviar', function () {
	$pelicula = Pelicula::first();

	Mail::to('carlos.barreiro@imaginanet.com')->send(new FichaPelicula($pelicula));

	return "Enviado";
});

Route::get('/email/previsualizar', function () {
	$pelicula = Pelicula::first();

	return new FichaPelicula($pelicula);
});

Route::get('/email', function () {
		Mail::raw('Que tal te va', function ($message) {
			$message->subject('Hola')->to('carlos.barreiro@imaginanet.com');
		});

		return "enviado";
	})->name('email');

Route::get('/creartoken', function () {

	$user = Auth::user();

	$token = $user->createToken('El nombre que queramos')->accessToken;

	return $token;

})->middleware('auth');

Route::get('/pruebapeliculas', function () {
	return Pelicula::all();
})->name('nombre');

Route::middleware('auth')->prefix('pruebas')->group(function () {

	Route::get('/nombre', function () {
		return Auth::user()->name;
	})->name('nombre');

	

});

Route::get('/test', function () {
 $pelicula = new Pelicula;
 $pelicula->identificador = "rambo";
 $pelicula->titulo = "Rambo";
 $pelicula->ano = 1982;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rambo-ii";
 $pelicula->titulo = "Rambo II";
 $pelicula->ano = 1985;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rambo-iii";
 $pelicula->titulo = "Rambo III";
 $pelicula->ano = 1988;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "john-rambo";
 $pelicula->titulo = "John Rambo";
 $pelicula->ano = 2008;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky";
 $pelicula->titulo = "Rocky";
 $pelicula->ano = 1976;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-ii";
 $pelicula->titulo = "Rocky II";
 $pelicula->ano = 1979;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-iii";
 $pelicula->titulo = "Rocky III";
 $pelicula->ano = 1982;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-iv";
 $pelicula->titulo = "Rocky IV";
 $pelicula->ano = 1986;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-v";
 $pelicula->titulo = "Rocky V";
 $pelicula->ano = 1990;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-balboa";
 $pelicula->titulo = "Rocky Balboa";
 $pelicula->ano = 2006;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "creed";
 $pelicula->titulo = "Creed";
 $pelicula->ano = 2016;
 $pelicula->save();
});

Route::get('/test2', function () {
 $productor = new Productor;
 $productor->nombre = "Sony";
 $productor->save();
 $productor = new Productor;
 $productor->nombre = "Disney";
 $productor->save();
 $productor = new Productor;
 $productor->nombre = "Fox";
 $productor->save();
 $productor = new Productor;
 $productor->nombre = "Warner Bros";
 $productor->save();
 $productor = new Productor;
 $productor->nombre = "MGM";
 $productor->save();
 $genero = new Genero;
 $genero->identificador = 'accion';
 $genero->nombre = 'Acción';
 $genero->save();
 $genero = new Genero;
 $genero->identificador = 'comedia';
 $genero->nombre = 'Comedia';
 $genero->save();
 $genero = new Genero;
 $genero->identificador = 'drama';
 $genero->nombre = 'Drama';
 $genero->save();
 $genero = new Genero;
 $genero->identificador = 'terror';
 $genero->nombre = 'Terror';
 $genero->save();
});

Route::get('/{locale}/peliculas', 'PeliculaController@index')->middleware('idioma');

Route::resource('peliculas', 'PeliculaController');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

resources/views/basico.blade.php
<!doctype html>
<html lang="es">
<head>
 <meta charset="UTF-8">
 <title>Curso</title>
</head>
<body>
<p>Página principal del curso mediante una vista.</p>
</body>
</html>

resources/views/cabecera.blade.php
<h1> Cabecera {{$title2}} </h1>

resources/views/formulario.blade.php
@extends('layouts.base', ['title' => 'Formulario'])

@section('body')
<p>
	<a href="{{ route('peliculas.index') }}">Peliculas de accion</a>
</p>

<div class="circulo"></div>
<div class="circulo grande"></div>

	<h1>Introducir película</h1>

	@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
					<li>{{$error}}</li>
				@endforeach
			</ul>
		</div>
	@endif

	<form action="{{ url('/') }}" method="POST" enctype="multipart/form-data" >
		{{csrf_field()}}
		<p>
			<label for="titulo">Título</label>
			<input type="text" id="titulo" name="titulo" placeholder="Título" value="{{old('titulo')}}" />
		</p>
		<p>
			<label for="ano">Año</label>
			<input type="number" id="ano" name="ano" placeholder="Año" value="{{old('ano')}}" />
		</p>

		<p>
			<label for="poster">Poster</label>
			<input type="file" id="poster" name="poster"  />
		</p>

		<p>
			<button>Enviar</button>
		</p>
	</form>
@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/larga.blade.php
@extends('layouts.base', ['title' => 'Pagina que no sirve para nada'])

@section('body')
<a href="{{ route('principal') }}">Ruta principal</a>
@stop

resources/views/peliculas.blade.php
@extends('layouts.base', [ 'title' => 'Peliculas'])

@section('estilos')
	@parent
	<link rel="stylesheet" href="peliculas.css" />
@stop

@section ('body')
	<p>Peliculas de {{$genero}}</p>
@stop

@section ('body2')
hola
@stop

resources/views/pie.blade.php
<small>© 2012 - 2018</small>