routes/web.php
<?php

use \App\Pelicula;
use \App\Productor;
use \App\Genero;
use \App\Mail\FichaPelicula;

Route::get('/email/enviar', function () {
	$pelicula = Pelicula::first();

	Mail::to('carlos.barreiro@imaginanet.com')->send(new FichaPelicula($pelicula));

	return "Enviado";
});

Route::get('/email/previsualizar', function () {
	$pelicula = Pelicula::first();

	return new FichaPelicula($pelicula);
});

Route::get('/email', function () {
		Mail::raw('Que tal te va', function ($message) {
			$message->subject('Hola')->to('carlos.barreiro@imaginanet.com');
		});

		return "enviado";
	})->name('email');

Route::get('/creartoken', function () {

	$user = Auth::user();

	$token = $user->createToken('El nombre que queramos')->accessToken;

	return $token;

})->middleware('auth');

Route::get('/pruebapeliculas', function () {
	return Pelicula::all();
})->name('nombre');

Route::middleware('auth')->prefix('pruebas')->group(function () {

	Route::get('/nombre', function () {
		return Auth::user()->name;
	})->name('nombre');

	

});

Route::get('/test', function () {
 $pelicula = new Pelicula;
 $pelicula->identificador = "rambo";
 $pelicula->titulo = "Rambo";
 $pelicula->ano = 1982;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rambo-ii";
 $pelicula->titulo = "Rambo II";
 $pelicula->ano = 1985;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rambo-iii";
 $pelicula->titulo = "Rambo III";
 $pelicula->ano = 1988;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "john-rambo";
 $pelicula->titulo = "John Rambo";
 $pelicula->ano = 2008;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky";
 $pelicula->titulo = "Rocky";
 $pelicula->ano = 1976;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-ii";
 $pelicula->titulo = "Rocky II";
 $pelicula->ano = 1979;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-iii";
 $pelicula->titulo = "Rocky III";
 $pelicula->ano = 1982;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-iv";
 $pelicula->titulo = "Rocky IV";
 $pelicula->ano = 1986;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-v";
 $pelicula->titulo = "Rocky V";
 $pelicula->ano = 1990;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "rocky-balboa";
 $pelicula->titulo = "Rocky Balboa";
 $pelicula->ano = 2006;
 $pelicula->save();
 $pelicula = new Pelicula;
 $pelicula->identificador = "creed";
 $pelicula->titulo = "Creed";
 $pelicula->ano = 2016;
 $pelicula->save();
});

Route::get('/test2', function () {
 $productor = new Productor;
 $productor->nombre = "Sony";
 $productor->save();
 $productor = new Productor;
 $productor->nombre = "Disney";
 $productor->save();
 $productor = new Productor;
 $productor->nombre = "Fox";
 $productor->save();
 $productor = new Productor;
 $productor->nombre = "Warner Bros";
 $productor->save();
 $productor = new Productor;
 $productor->nombre = "MGM";
 $productor->save();
 $genero = new Genero;
 $genero->identificador = 'accion';
 $genero->nombre = 'Acción';
 $genero->save();
 $genero = new Genero;
 $genero->identificador = 'comedia';
 $genero->nombre = 'Comedia';
 $genero->save();
 $genero = new Genero;
 $genero->identificador = 'drama';
 $genero->nombre = 'Drama';
 $genero->save();
 $genero = new Genero;
 $genero->identificador = 'terror';
 $genero->nombre = 'Terror';
 $genero->save();
});

Route::get('/{locale}/peliculas', 'PeliculaController@index')->middleware('idioma');

Route::resource('peliculas', 'PeliculaController');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/Pelicula.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pelicula extends Model
{
	protected $fillable = ['titulo', 'ano', 'identificador', 'poster', 'productora_id'];

	public function productora()
	{
		return $this->belongsTo('App\Productor', 'productora_id');
	}

	public function generos() {
		return $this->belongsToMany('App\Genero');
	}

    public function scopeRockySaga($query) {
    	return $query->where('identificador', 'LIKE', '%rocky%')->orWhere('identificador', 'LIKE', '%creed%');
    }

    public function getRouteKeyName() {
    	return 'identificador';
    }

    public static function generateUniqueSlug($titulo) {
    	$originalSlug = str_slug($titulo);

    	$i = 1;
    	$slug = $originalSlug;
    	$exists = Pelicula::where('identificador', $slug)->count();

    	while ($exists) {
    		$slug = $originalSlug . '-' . $i;
    		$exists = Pelicula::where('identificador', $slug)->count();

    		$i++;
    	}

    	return $slug;
    }
}

app/Http/Controllers/PeliculaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Pelicula;
use App\Productor;
use App\Genero;
use View;
use Auth;

class PeliculaController extends Controller
{

    public function __construct() {

        $this->middleware(function ($request, $next) {
            if (!$request->wantsJson()) {
                if (Auth::guest()) {
                    abort('403', "A donde vas");
                }
            }
            
            return $next($request);
        })->except('index', 'show');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $peliculas = Pelicula::orderBy('ano', 'desc')->paginate(5);

        if ($request->wantsJson()) {
            return $peliculas;
        }

        return View::make('peliculas.index', compact('peliculas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $productoras = Productor::all();
        $generos = Genero::all();
        return View::make('peliculas.create', compact('productoras', 'generos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'titulo' => 'required|string|max:200',
            'ano' => 'required|integer|min:1900|max:2020',
            'poster' => 'image',
            'productora_id' => 'required|exists:productoras,id',
            'generos' => 'required|array',
            'generos.*' => 'exists:generos,id',
        ]);

        $properties = $request->only('titulo', 'ano', 'productora_id');

        $properties['identificador'] = Pelicula::generateUniqueSlug($request->get('titulo'));

        if ($request->has('poster')) {
            $archivo = $request->file('poster');
            $nombreArchivo = $archivo->getClientOriginalName();
            $archivo->move(public_path() . '/uploads/', $nombreArchivo);

            $properties['poster'] = '/uploads/' . $nombreArchivo;
        }

        $pelicula = Pelicula::create($properties);

        $pelicula->generos()->sync($request->get('generos'));

        if ($request->wantsJson()) {
            return $pelicula;
        }

        return redirect(route('peliculas.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Pelicula $pelicula, Request $request)
    {
        if ($request->wantsJson()) {
            return $pelicula;
        }
        return View::make('peliculas.detail', compact('pelicula'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Pelicula $pelicula)
    {
        $productoras = Productor::all();
        $generos = Genero::all();
        return View::make('peliculas.edit', compact('pelicula', 'productoras', 'generos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pelicula $pelicula)
    {
        $request->validate([
            'titulo' => 'required|string|max:200',
            'ano' => 'required|integer|min:1900|max:2020',
            'poster' => 'image',
            'productora_id' => 'required|exists:productoras,id',
            'generos' => 'required|array',
            'generos.*' => 'exists:generos,id',
        ]);

        $properties = $request->only('titulo', 'ano', 'productora_id');

        if ($request->has('poster')) {
            $archivo = $request->file('poster');
            $nombreArchivo = $archivo->getClientOriginalName();
            $archivo->move(public_path() . '/uploads/', $nombreArchivo);

            $properties['poster'] = '/uploads/' . $nombreArchivo;
        }

        $pelicula->fill($properties);

        $pelicula->generos()->sync($request->get('generos'));

        $pelicula->save();

        if ($request->wantsJson()) {
            return $pelicula;
        }

        return redirect(route('peliculas.show', $pelicula));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pelicula $pelicula, Request $request)
    {
        $pelicula->delete();

        if ($request->wantsJson()) {
            return ['status' => 'ok'];
        }

        return redirect(route('peliculas.index'));
    }
}

resources/views/peliculas/create.blade.php
@extends('layouts.app', ['title' => 'Formulario'])

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Introducir película</div>

                <div class="panel-body">

					@if ($errors->any())
						<div class="alert alert-danger">
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{$error}}</li>
								@endforeach
							</ul>
						</div>
					@endif

					<form action="{{ route('peliculas.store') }}" method="POST" enctype="multipart/form-data" >
						{{csrf_field()}}
						<p>
							<label for="titulo">Título</label>
							<input type="text" id="titulo" name="titulo" placeholder="Título" value="{{old('titulo')}}" />
						</p>
						<p>
							<label for="ano">Año</label>
							<input type="number" id="ano" name="ano" placeholder="Año" value="{{old('ano')}}" />
						</p>

						<p>
							<label for="poster">Poster</label>
							<input type="file" id="poster" name="poster"  />
						</p>

						<p>
							<label for="productora_id">Productora</label>
							<select id="productora_id" name="productora_id">
								<option selected disabled>Seleccionar productora</option>
								@foreach ($productoras as $productora)
									<option value="{{$productora->id}}" 
										@if (old('productora_id')==$productora->id) 
											selected 
										@endif 
										> {{$productora->nombre}} </option>
								@endforeach
								<option value="estoestamal">A ver que pasa</option>
							</select>
						</p>

						<p>
							<label for="generos">Generos</label>
							<select id="generos" name="generos[]" multiple>
								@foreach ($generos as $genero)
									<option value="{{$genero->id}}" 
										@if (old('generos') && in_array($genero->id, old('generos')))
											selected
										@endif
										> {{$genero->nombre}} </option>
								@endforeach
							</select>
						</p>

						<p>
							<button>Enviar</button>
						</p>
					</form>
                </div>
            </div>
        </div>
    </div>
</div>


@stop

resources/views/peliculas/detail.blade.php
@extends('layouts.app', ['title' => 'Pelicula' . $pelicula->titulo])

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Pelicula: {{$pelicula->titulo}}</div>

                <div class="panel-body">
                    <h3>Año: {{$pelicula->ano}}</h3>

					@if ($pelicula->poster)
						<img src="{{url($pelicula->poster)}}" />
					@endif

					@if ($pelicula->productora)
						<p>
							Productora: {{$pelicula->productora->nombre}}
						</p>
					@endif

					@if ($pelicula->generos && $pelicula->generos->count()>0)
						<p>
							Géneros: {{$pelicula->generos->implode('nombre', ', ')}}
						</p>
					@endif

					<p>
						<a href="{{route('peliculas.edit', $pelicula)}}">Editar película</a>
					</p>
                </div>
            </div>
        </div>
    </div>
</div>

@include('peliculas.random')
	
@stop

resources/views/peliculas/edit.blade.php
@extends('layouts.app', ['title' => 'Formulario'])

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Editar película {{$pelicula->titulo}}</div>

                <div class="panel-body">
                    @if ($errors->any())
						<div class="alert alert-danger">
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{$error}}</li>
								@endforeach
							</ul>
						</div>
					@endif

					<form action="{{ route('peliculas.update', $pelicula) }}" method="POST" enctype="multipart/form-data" >
						{{csrf_field()}}
						{{method_field('PUT')}}

						<p>
							<label for="titulo">Título</label>
							<input type="text" id="titulo" name="titulo" placeholder="Título" value="{{old('titulo', $pelicula->titulo)}}" />
						</p>
						<p>
							<label for="ano">Año</label>
							<input type="number" id="ano" name="ano" placeholder="Año" value="{{old('ano', $pelicula->ano)}}" />
						</p>

						<p>
							<label for="poster">Poster</label>
							@if ($pelicula->poster)
								<img src="{{url($pelicula->poster)}}" />
							@endif
							<input type="file" id="poster" name="poster"  />
						</p>

						<p>
							<label for="productora_id">Productora</label>
							<select id="productora_id" name="productora_id">
								@if ($pelicula->productora)
									<option selected disabled>Seleccionar productora</option>
								@endif
								@foreach ($productoras as $productora)
									<option value="{{$productora->id}}" 
										@if (old('productora_id', $pelicula->productora_id)==$productora->id) 
											selected 
										@endif 
										> {{$productora->nombre}} </option>
								@endforeach
							</select>
						</p>

						<p>
							<label for="generos">Generos</label>
							<select id="generos" name="generos[]" multiple>
								@foreach ($generos as $genero)
									<option value="{{$genero->id}}" 
				@if (in_array($genero->id, old('generos', $pelicula->generos->pluck('id')->toArray())))
											selected
										@endif
										> {{$genero->nombre}} </option>
								@endforeach
							</select>
						</p>

						<p>
							<button>Enviar</button>
						</p>
					</form>

					<form action="{{route('peliculas.destroy', $pelicula)}}" method="POST">
						{{csrf_field()}}
						{{method_field('DELETE')}}
						<p>
							<input type="submit" value="Eliminar" />
						</p>
					</form>
                </div>
            </div>
        </div>
    </div>
</div>


	

@stop

resources/views/peliculas/index.blade.php
@extends('layouts.app', ['title' => 'Peliculas'])

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">@lang('curso.peliculas.cabecera')</div>

                <div class="panel-body">
                    <table>
						<thead>
							<tr>
								<td>@lang('curso.titulo')</td>
								<td>@lang('curso.ano')</td>
								@guest
								@else
								<td>@lang('curso.editar')</td>
								@endguest
							</tr>
						</thead>
						<tbody>
							@forelse ($peliculas as $pelicula)
								<tr>
									<td><a href="{{route('peliculas.show', ['peliculas' => $pelicula])}}">{{$pelicula->titulo}}</a></td>
									<td>{{$pelicula->ano}}</td>
									@auth
									<td><a href="{{route('peliculas.edit', $pelicula)}}">@lang('curso.editar')</a></td>
									@endauth
								</tr>
							@empty
								No hay películas
							@endforelse
						</tbody>
					</table>

					{{$peliculas->links()}}

					@auth
					<a href="{{route('peliculas.create')}}">@lang('curso.peliculas.crear')</a>
					@endauth
                </div>
            </div>
        </div>
    </div>
</div>

@include('peliculas.random')
	
@stop

resources/views/peliculas/random.blade.php
<h1>Película destacada</h1>

<a href="{{route('peliculas.show', $pelicula)}}">{{$pelicula->titulo}}</a>